# biz_server.toml

ver = "0.0.1"
#logPath = "/tmp/frontend.log"
serverId = 1

[server80]
name = "frontend80"
protoName = "mtproto"
addr = "0.0.0.0:8000"
# 80

[server443]
name = "frontend443"
protoName = "mtproto"
addr = "0.0.0.0:12345"
# 43

[server5222]
name = "frontend5222"
protoName = "mtproto"
addr = "0.0.0.0:5222"
# 5222

[sessionClient]
name = "session"
protoName = "zproto"
addrList = ["127.0.0.1:10000"]
balancer = "round_robin"
